### ISSUE TITLE
How to disable Parent component scrollbar?

### ISSUE THREAD

**Issue by sadashivm** [RobPethick/react-custom-scrollbars-2#35]
I have child component inside Parent component and both components have scrollbar. In some scenario I want to disable parent component scrollbar.

How should I achieve?

Can you please help me?

**Comment by samyan** [comment]
Just put this in the parent css

```css
.parent-component {
    overflow: hidden;
}

```
